#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pytest-rerunfailures
Version  : 8.0
Release  : 12
URL      : https://files.pythonhosted.org/packages/a8/12/3879570e273d3fe10bb836aa5417476efe3d1a316690b1c9455c5b922e17/pytest-rerunfailures-8.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/a8/12/3879570e273d3fe10bb836aa5417476efe3d1a316690b1c9455c5b922e17/pytest-rerunfailures-8.0.tar.gz
Summary  : pytest plugin to re-run tests to eliminate flaky failures
Group    : Development/Tools
License  : MPL-2.0
Requires: pytest-rerunfailures-license = %{version}-%{release}
Requires: pytest-rerunfailures-python = %{version}-%{release}
Requires: pytest-rerunfailures-python3 = %{version}-%{release}
Requires: pytest
Requires: setuptools
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
pytest-rerunfailures
====================
pytest-rerunfailures is a plugin for `py.test <http://pytest.org>`_ that
re-runs tests to eliminate intermittent failures.

%package license
Summary: license components for the pytest-rerunfailures package.
Group: Default

%description license
license components for the pytest-rerunfailures package.


%package python
Summary: python components for the pytest-rerunfailures package.
Group: Default
Requires: pytest-rerunfailures-python3 = %{version}-%{release}

%description python
python components for the pytest-rerunfailures package.


%package python3
Summary: python3 components for the pytest-rerunfailures package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pytest-rerunfailures package.


%prep
%setup -q -n pytest-rerunfailures-8.0
cd %{_builddir}/pytest-rerunfailures-8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1574092519
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pytest-rerunfailures
cp %{_builddir}/pytest-rerunfailures-8.0/LICENSE %{buildroot}/usr/share/package-licenses/pytest-rerunfailures/34074d4fbfebc874082235b72690a954af4fb07c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pytest-rerunfailures/34074d4fbfebc874082235b72690a954af4fb07c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
